"""Initial revision

Revision ID: b2992bc91b4e
Revises: 
Create Date: 2025-04-07 15:56:06.159832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2992bc91b4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id_master', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('player_status',
    sa.Column('id_player', sa.Integer(), nullable=False),
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CIVILIAN', 'MAFIA', 'DON', 'SHERIFF', name='roleenum'), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ALIVE', 'DEAD', name='statusenum'), nullable=False),
    sa.Column('elimination_reason', sa.Enum('VOTED', 'KILLED', 'DELETED', name='eliminationreasonenum'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_game'], ['game.id'], ),
    sa.ForeignKeyConstraint(['id_player'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_status')
    op.drop_table('player')
    op.drop_table('game')
    # ### end Alembic commands ###
