"""Initial revision

Revision ID: ee7f3ce32175
Revises: b2992bc91b4e
Create Date: 2025-05-01 02:41:21.305976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7f3ce32175'
down_revision: Union[str, None] = 'b2992bc91b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_email_key', 'player', type_='unique')
    op.drop_column('player', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('player_email_key', 'player', ['email'])
    # ### end Alembic commands ###
