/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClockArea: typeof import('./components/ClockArea.vue')['default']
    CreatingGame: typeof import('./components/CreatingGame.vue')['default']
    FunctionButtons: typeof import('./components/FunctionButtons.vue')['default']
    InfoStageArea: typeof import('./components/InfoStageArea.vue')['default']
    PlayerCard: typeof import('./components/PlayerCard.vue')['default']
    PlayerNicknameForm: typeof import('./components/PlayerNicknameForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartOnlineGame: typeof import('./components/StartOnlineGame.vue')['default']
  }
}
